# ----
# Site

title: ServiceStack Docs
description: Documentation for the ServiceStack Framework
url: http://servicestack.github.io/docs/
repository: ServiceStack/docs
google_analytics_key:

collections:
  documentation:
    title: Documentation
    output: true
gems:
  - github-pages

exclude:
  - readme.md
  - LICENCE

topics: []
sorted_topics: {}
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed
