# ----
# Site

title: ServiceStack Docs
description: Documentation for the ServiceStack Framework
url: http://servicestack.github.io/docs/
repository: ServiceStack/docs
google_analytics_key:

collections:
  documentation:
    title: Documentation
    output: true
    permalink: /:slug.html
  releases:
    title: Release Notes
    output: true
    permalink: /releases/:slug.html    
gems:
  - github-pages

exclude:
  - readme.md
  - LICENCE

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: documentation
    values:
      priority: 999

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed
